name: Build Android AAB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli
      
    - name: Add Android platform
      run: npx cap add android
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Generate debug keystore
      run: |
        keytool -genkey -v -keystore debug.keystore -alias debug -keyalg RSA -keysize 2048 -validity 10000 \
          -dname "CN=Debug,OU=Debug,O=Debug,L=Debug,S=Debug,C=US" \
          -storepass android -keypass android
        
    - name: Create keystore.properties
      run: |
        echo "storeFile=../../debug.keystore" > android/keystore.properties
        echo "storePassword=android" >> android/keystore.properties
        echo "keyAlias=debug" >> android/keystore.properties
        echo "keyPassword=android" >> android/keystore.properties
        
    - name: Update build.gradle for signing
      run: |
        sed -i '/android {/a\
        \    signingConfigs {\
        \        debug {\
        \            def props = new Properties()\
        \            props.load(new FileInputStream(file("keystore.properties")))\
        \            storeFile file(props["storeFile"])\
        \            storePassword props["storePassword"]\
        \            keyAlias props["keyAlias"]\
        \            keyPassword props["keyPassword"]\
        \        }\
        \    }' android/app/build.gradle
        
        sed -i '/buildTypes {/,/}/ {
          /debug {/a\
        \            signingConfig signingConfigs.debug
        }' android/app/build.gradle
        
    - name: Build Android AAB
      run: |
        cd android
        chmod +x gradlew
        ./gradlew bundleDebug
        
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-aab-${{ github.run_number }}
        path: android/app/build/outputs/bundle/debug/app-debug.aab
        retention-days: 30
        
    - name: Build Android APK (for testing)
      run: |
        cd android
        ./gradlew assembleDebug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-${{ github.run_number }}
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30